-- SKEMA DATABASE SP-MENTAL-PASKIBRA (SUPABASE/POSTGRESQL)

-- 1. Tabel Gangguan
CREATE TABLE gangguan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode VARCHAR(10) UNIQUE NOT NULL,
    nama VARCHAR(100) NOT NULL,
    deskripsi TEXT
);

-- 2. Tabel Gejala
CREATE TABLE gejala (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_gejala VARCHAR(10) UNIQUE NOT NULL,
    nama_gejala TEXT NOT NULL,
    kode_gangguan VARCHAR(10) REFERENCES gangguan(kode) ON DELETE SET NULL,
    aktif BOOLEAN DEFAULT TRUE
);

-- 3. Tabel Diagnosa Detail (Saran & Deskripsi Hasil)
CREATE TABLE diagnosa_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gangguan VARCHAR(50) NOT NULL,
    tingkat VARCHAR(20) NOT NULL,
    deskripsi TEXT NOT NULL,
    saran TEXT NOT NULL,
    rekomendasi VARCHAR(100) DEFAULT '-'
);

-- 4. Tabel Hasil Diagnosa
CREATE TABLE hasil_diagnosa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100),
    hasil_diagnosa VARCHAR(255),
    deskripsi TEXT,
    saran TEXT,
    rekomendasi TEXT,
    confidence FLOAT, -- Tracking akurasi model
    waktu_diagnosa TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabel Diagnosa Cache (Untuk efisiensi Render Free Tier)
CREATE TABLE diagnosa_cache (
    hash_input VARCHAR(64) PRIMARY KEY,
    result_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Tabel Rate Limiting (Mencegah abuse sistem gratisan)
CREATE TABLE rate_limits (
    identifier VARCHAR(100) PRIMARY KEY, -- Bisa IP atau Email
    request_count INT DEFAULT 1,
    last_request TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabel Users
CREATE TABLE users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nama VARCHAR(100),
    email VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role VARCHAR(20) DEFAULT 'Siswa',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Tabel Profil Siswa
CREATE TABLE user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL REFERENCES users(email) ON DELETE CASCADE,
    nama VARCHAR(100) NOT NULL,
    tgl_lahir DATE NOT NULL,
    jenis_kelamin VARCHAR(20) NOT NULL,
    alamat TEXT NOT NULL,
    no_telp VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Tabel Relasi Gejala-Gangguan
CREATE TABLE relasi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_gangguan VARCHAR(10) NOT NULL REFERENCES gangguan(kode) ON DELETE CASCADE,
    kode_gejala VARCHAR(10) NOT NULL REFERENCES gejala(kode_gejala) ON DELETE CASCADE,
    bobot FLOAT DEFAULT 1,
    UNIQUE (kode_gangguan, kode_gejala)
);

-- TAMBAHKAN INDEX UNTUK PERFORMA
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_gejala_kode ON gejala(kode_gejala);
CREATE INDEX idx_hasil_diagnosa_email ON hasil_diagnosa(email);
CREATE INDEX idx_hasil_diagnosa_waktu ON hasil_diagnosa(waktu_diagnosa);
CREATE INDEX idx_diagnosa_detail_lookup ON diagnosa_detail(gangguan, tingkat);
CREATE INDEX idx_user_profile_email ON user_profile(email);
CREATE INDEX idx_relasi_gangguan ON relasi(kode_gangguan);
CREATE INDEX idx_relasi_gejala ON relasi(kode_gejala);
